version: "3.8"

services:
  shared-libs:
    build:
      context: .
      dockerfile: Dockerfile.shared-libs
    volumes:
      - shared-libs-volume:/app/shared-libs
    networks:
      - microfrontend-network

  mfe-host:
    build: ./mfe-host
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./mfe-host:/app
      - /app/node_modules
      - shared-libs-volume:/app/shared-libs:ro
      - ./mfe-common-components:/app/node_modules/mfe-common-components:ro
    depends_on:
      - shared-libs
      - mfe-catalog
      - mfe-cart
      - mfe-checkout
    networks:
      - microfrontend-network

  mfe-catalog:
    build: ./mfe-catalog
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./mfe-catalog:/app
      - /app/node_modules
      - shared-libs-volume:/app/shared-libs:ro
      - ./mfe-common-components:/app/node_modules/mfe-common-components:ro
    depends_on:
      - shared-libs
    networks:
      - microfrontend-network

  mfe-cart:
    build: ./mfe-cart
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./mfe-cart:/app
      - /app/node_modules
      - shared-libs-volume:/app/shared-libs:ro
      - ./mfe-common-components:/app/node_modules/mfe-common-components:ro
    depends_on:
      - shared-libs
    networks:
      - microfrontend-network

  mfe-checkout:
    build: ./mfe-checkout
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./mfe-checkout:/app
      - /app/node_modules
      - shared-libs-volume:/app/shared-libs:ro
      - ./mfe-common-components:/app/node_modules/mfe-common-components:ro
    depends_on:
      - shared-libs
    networks:
      - microfrontend-network

volumes:
  shared-libs-volume:

networks:
  microfrontend-network:
    driver: bridge
